name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy-prod:
    environment: production
    steps:
    - run: echo production environment deployed
  deploy-staging:
    environment: staging
    steps:
    - run: echo staging environment deployed
  deploy-test:
    environment: testing
    steps:
      - run: echo testing environment deployed
